[package]
name = "hello_world_website"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
dotenv = "0.15"
tera = "1.2"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "hello_world_website"
path = "src/main.rs"
